blank_issues_enabled: false
contact_links:
  - name: Reportar una vulnerabilidad
    url: https://github.com/adrielcrv/raudo-windows/security/advisories/new
    about: Utiliza el canal privado para problemas de seguridad.
